Feature/user module
Seelen-Inc/slu-lib pull request #6
Opened 2024-12-20 12:34 UTC by luriusTM

2025-01-28 20:27 UTC, eythaann requested changes

2025-01-28 20:27 UTC, eythaann commented on src/system_state/user.rs
> +    pub fn to_path(&self) -> PathBuf {
paths could change by user settings on registry, this needs Windows API, so remove this and add then to the Application

2025-01-28 20:27 UTC, eythaann commented on src/system_state/user.rs
> +const RECENT_FOLDER_RELATIVE_PATH: &str = "..\\..\\Roaming\\Microsoft\\Windows\\Recent";
remove this entire list of paths

2025-01-28 20:27 UTC, eythaann commented on src/utils/State.ts
> +export function createInstanceInvokerWithArgs<
remove this, just add the args as an optional argument on the `createInstanceInvoker`

2025-01-28 20:38 UTC, luriusTM commented on src/utils/State.ts
> +export function createInstanceInvokerWithArgs<
The argument here propagated to the consumer layer, can not be determined at creation time. So this command do not accept an argument when the method created, but creates a method which has the argument to pass to the command.

2025-02-01 03:34 UTC, eythaann approved these changes

2025-02-01 03:34 UTC, eythaann commented on src/utils/State.ts
> +export function createInstanceInvokerWithArgs<
I will change this to no wait, but you have `_getAsync` and `_setFolderLimit` that are duplicated code. so, this function is in really is not needed, it was just a bad design pattern. I will clean this after merge so, you can see the changes later.

2025-02-01 03:35 UTC, merged